# Cameron Seibel
#
# This script compiles a vector describing a countries development status in 2016.
# The data is sourced from the UN, it was a pain to clean.

developed_countries <- c(
  "Austria",
  "Belgium",
  "Denmark",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Ireland",
  "Italy",
  "Luxembourg",
  "Netherlands",
  "Portugal",
  "Spain",
  "Sweden",
  "United Kingdom",
  "Bulgaria",
  "Croatia",
  "Cyprus",
  "Czech Republic",
  "Estonia",
  "Hungary",
  "Latvia",
  "Lithuania",
  "Malta",
  "Poland",
  "Romania",
  "Slovakia",
  "Slovenia",
  "Iceland",
  "Norway",
  "Switzerland",
  "Australia",
  "Canada",
  "Japan",
  "New Zealand",
  "United States",
  "Canada",
  "Japan",
  "France",
  "Germany",
  "Italy",
  "United Kingdom",
  "United States"
)